services:
  web:
    build:
      context: ./app
    ports:
      - "80:80"
    environment:
      - API_URL=http://localhost:9200 # Set the backend URL here
    volumes:
      - ./app/nginx.conf:/etc/nginx/nginx.conf
      - ./app/entrypoint.sh:/entrypoint.sh
    command: ["/entrypoint.sh"]

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    ports:
      - "9113:9113"
    depends_on:
      - web
    command: -nginx.scrape-uri=http://web/status

  opensearch:
    image: opensearchproject/opensearch:2.17.1
    ports:
      - "9200:9200"
      - "9600:9600"
    environment:
      - discovery.type=single-node
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=$OPENSEARCH_PASSWORD
      - plugins.security.disabled=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - nginx-exporter
      - opensearch
    
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=$GF_SECURITY_ADMIN_PASSWORD
      - GF_PROVISIONING_ENABLED=true


