global:
  scrape_interval: 15s # Default scrape interval

scrape_configs:
  - job_name: "nginx"
    static_configs:
      - targets: ["nginx-exporter:9113"]

  - job_name: "opensearch"
    static_configs:
      - targets: ["opensearch:9200"]
    metrics_path: "/_prometheus/metrics"
